name: masker
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - flask
  - scikit-learn
  - numpy
  - matplotlib
  - pillow
  - pyyaml
  - pip
  - pip:
    - opencv-python

